language: python
notifications:
  email: false
dist: xenial
python:
- "3.5"
- "3.6"
- "3.7"
before_install:
- sudo add-apt-repository -y ppa:jonathonf/backports
- sudo apt-get -qq update
- sudo apt-get install -y libopenjp2-7
install:
- pip install .
- pip install -r requirements-dev.txt
script:
- pylint s2cloudless/*.py
- radon cc sentinelhub/*.py -a -nb
- pytest --cov ./tests/
